-- version 0.5
-- RCS 추가 테이블
-- 변경이력
--- 20201106 SURVEY_RCS:RCS_MSG_TYPE, SLIDE_CNT  자료형 변경

-- RCS 슬라이드별 정보(SURVEY_SEQ 1개당 최대 6개 슬라이드)
CREATE TABLE MMADMIN.SURVEY_RCS(
    RCS_SEQ		    NUMBER(18) NOT NULL,
    SURVEY_SEQ		    NUMBER(18) NOT NULL,
    RCS_MSG_TYPE            VARCHAR(20) NOT NULL,
    SLIDE_CNT               NUMBER(3) NOT NULL,
    FOOTER_PHONE_NUM        VARCHAR2(20) NOT NULL,
    TITLE_MSG_1	            VARCHAR2(100) NULL,
    GUIDE_MSG_1	            VARCHAR2(4000) NULL,
    IMG_FILE_PATH_1         VARCHAR2(500) NULL,
    IMG_FILE_URL_1          VARCHAR2(300) NULL,
    TITLE_MSG_2	            VARCHAR2(100) NULL,    
    GUIDE_MSG_2	            VARCHAR2(4000) NULL,    
    IMG_FILE_PATH_2         VARCHAR2(500) NULL,
    IMG_FILE_URL_2          VARCHAR2(300) NULL,
    TITLE_MSG_3	            VARCHAR2(100) NULL,
    GUIDE_MSG_3	            VARCHAR2(4000) NULL,
    IMG_FILE_PATH_3         VARCHAR2(500) NULL,
    IMG_FILE_URL_3          VARCHAR2(300) NULL,
    TITLE_MSG_4             VARCHAR2(100) NULL,
    GUIDE_MSG_4             VARCHAR2(4000) NULL,
    IMG_FILE_PATH_4         VARCHAR2(500) NULL,
    IMG_FILE_URL_4          VARCHAR2(300) NULL,
    TITLE_MSG_5	            VARCHAR2(100) NULL,
    GUIDE_MSG_5	            VARCHAR2(4000) NULL,
    IMG_FILE_PATH_5         VARCHAR2(500) NULL,
    IMG_FILE_URL_5          VARCHAR2(300) NULL,
    TITLE_MSG_6             VARCHAR2(100) NULL,
    GUIDE_MSG_6	            VARCHAR2(4000) NULL,
    IMG_FILE_PATH_6         VARCHAR2(500) NULL,
    IMG_FILE_URL_6          VARCHAR2(300) NULL
)
TABLESPACE TS_TMM_DAT01
STORAGE
(
INITIAL 10M
NEXT 10M
)
NOCOMPRESS;

CREATE INDEX MMADMIN.IDX1_SURVEY_RCS
ON MMADMIN.SURVEY_RCS (SURVEY_SEQ);

ALTER TABLE MMADMIN.SURVEY_RCS
ADD CONSTRAINT  PK_SURVEY_RCS PRIMARY KEY (RCS_SEQ);

CREATE SEQUENCE MMADMIN.RCS_SEQ
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 999999999999999999;

GRANT SELECT ON MMADMIN.RCS_SEQ TO MMUSER;

GRANT DELETE ON MMADMIN.SURVEY_RCS TO MMUSER;
GRANT UPDATE ON MMADMIN.SURVEY_RCS TO MMUSER;
GRANT SELECT ON MMADMIN.SURVEY_RCS TO MMUSER;
GRANT INSERT ON MMADMIN.SURVEY_RCS TO MMUSER;

CREATE SYNONYM MMUSER.SURVEY_RCS FOR MMADMIN.SURVEY_RCS;
CREATE SYNONYM MMUSER.RCS_SEQ FOR MMADMIN.RCS_SEQ;



-- 슬라이드별 버튼정보(최대 2개)
CREATE TABLE MMADMIN.SURVEY_RCS_BTN(
    RCS_SEQ		        NUMBER(18) NOT NULL,
    RCS_SLIDE_ORD       NUMBER(3) NOT NULL,
    BTN_TYPE_1          VARCHAR2(10) NULL,  -- URL연결/지도보여주기/매장위치/내위치/전화걸기/일정/메시지보내기/복사
    BTN_NAME_1          VARCHAR2(20) NULL,  -- display/버튼명
    ACT_URL_1	        VARCHAR2(300) NULL, -- URL주소
    ACT_PHONE_NUM_1     VARCHAR2(20) NULL,  -- 전화번호
    ACT_PHONE_MSG_1     VARCHAR2(300) NULL, -- 전화번호
    GEO_NAME_1          VARCHAR2(100) NULL, -- Label/위치이름
    GEO_URL_1		    VARCHAR2(300) NULL, -- 위치URL
    GEO_LATI_1          NUMBER NULL,        -- 위도
    GEO_LOTI_1          NUMBER NULL,        -- 경도
    CPY_MSG_1           VARCHAR2(300) NULL, -- 복사내용
    CAL_NAME_1          VARCHAR2(50) NULL,  -- 일정제목
    CAL_DESC_1          VARCHAR2(300) NULL, -- 일정내용
    CAL_START_DTTM_1    DATE,               -- 시작시간
    CAL_END_DTTM_1      DATE,               -- 종료시간
    BTN_TYPE_2          VARCHAR2(10) NULL,  
    BTN_NAME_2          VARCHAR2(20) NULL,  
    ACT_URL_2	        VARCHAR2(300) NULL, 
    ACT_PHONE_NUM_2     VARCHAR2(20) NULL,  
    ACT_PHONE_MSG_2     VARCHAR2(300) NULL, 
    GEO_NAME_2          VARCHAR2(100) NULL, 
    GEO_URL_2		    VARCHAR2(300) NULL, 
    GEO_LATI_2          NUMBER NULL,
    GEO_LOTI_2          NUMBER NULL,
    CPY_MSG_2           VARCHAR2(300) NULL, 
    CAL_NAME_2          VARCHAR2(50) NULL,  
    CAL_DESC_2          VARCHAR2(300) NULL, 
    CAL_START_DTTM_2    DATE,               
    CAL_END_DTTM_2      DATE
)
TABLESPACE TS_TMM_DAT01
STORAGE
(
INITIAL 10M
NEXT 10M
)
NOCOMPRESS;

CREATE INDEX MMADMIN.IDX1_SURVEY_RCS_BTN
ON MMADMIN.SURVEY_RCS_BTN (RCS_SEQ);

ALTER TABLE MMADMIN.SURVEY_RCS_BTN
ADD CONSTRAINT PK_SURVEY_RCS_BTN PRIMARY KEY (RCS_SEQ, RCS_SLIDE_ORD);

GRANT DELETE ON MMADMIN.SURVEY_RCS_BTN TO MMUSER;
GRANT UPDATE ON MMADMIN.SURVEY_RCS_BTN TO MMUSER;
GRANT SELECT ON MMADMIN.SURVEY_RCS_BTN TO MMUSER;
GRANT INSERT ON MMADMIN.SURVEY_RCS_BTN TO MMUSER;

CREATE SYNONYM MMUSER.SURVEY_RCS_BTN FOR MMADMIN.SURVEY_RCS_BTN;
