-- Admin사업자
CREATE TABLE MMADMIN.BLC (
	BLC_ID NUMBER NOT NULL,				-- Admin사업자ID
	BLC_CD VARCHAR2(20) NOT NULL, 		-- Admin사업자코드
	BLC_NM VARCHAR2(100) NOT NULL, 		-- Admin사업자명
	CRT_DTTM DATE DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 생성일시
	CRT_USER_ID VARCHAR2(20) NOT NULL, 	-- 생성유저ID
	CRT_PRGM_ID VARCHAR2(20) NOT NULL, 	-- 생성프로그램ID
	UPD_DTTM DATE DEFAULT CURRENT_TIMESTAMP NOT NULL, -- 수정일시
	UPD_USER_ID VARCHAR2(20) NOT NULL, 	-- 수정유저ID
	UPD_PRGM_ID VARCHAR2(20) NOT NULL, 	-- 수정프로그램ID
	BLC_DISP_NM VARCHAR2(100) 			-- Admin사업자전시명
)
TABLESPACE TS_TMM_DAT01
STORAGE
(
INITIAL 10M
NEXT 10M
)
NOCOMPRESS;

ALTER TABLE MMADMIN.BLC
ADD CONSTRAINT PK_BLC PRIMARY KEY (BLC_ID);

CREATE SEQUENCE MMADMIN.BLC_ID
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 999999999999999999;

GRANT SELECT ON MMADMIN.BLC_ID TO MMUSER;

GRANT DELETE ON MMADMIN.BLC TO MMUSER;
GRANT UPDATE ON MMADMIN.BLC TO MMUSER;
GRANT SELECT ON MMADMIN.BLC TO MMUSER;
GRANT INSERT ON MMADMIN.BLC TO MMUSER;

CREATE SYNONYM MMUSER.BLC FOR MMADMIN.BLC;
CREATE SYNONYM MMUSER.BLC_ID FOR MMADMIN.BLC_ID;

-- 중계사 테이블 컬럼 추가
ALTER TABLE RLC ADD (
    blc_id	NUMBER -- Admin사업자ID
);

-- 운영자 테이블 컬럼 추가
ALTER TABLE ADMIN ADD (
    blc_id	NUMBER -- Admin사업자ID 
);

-- 고객사 테이블 컬럼 추가
ALTER TABLE CUSTOM ADD (
    blc_id	NUMBER -- Admin사업자ID
);

-- 분리고객사 테이블 컬럼 추가
ALTER TABLE SEP_CUSTOM ADD (
    blc_id	NUMBER -- Admin사업자ID
);

-- 공지사항 테이블 컬럼 추가
ALTER TABLE NOTI ADD (
    blc_id	NUMBER -- Admin사업자ID
);

-- FAQ 테이블 컬럼 추가
ALTER TABLE FAQ ADD (
    blc_id	NUMBER -- Admin사업자ID
);

-- 1:1문의 테이블 컬럼 추가
ALTER TABLE QNA ADD (
    blc_id	NUMBER -- Admin사업자ID
);

-- 공통코드 컬럼 추가
ALTER TABLE COM_CD ADD (
    blc_id	NUMBER -- Admin사업자ID
);

-- 역할자원매핑 테이블 컬럼 추가
ALTER TABLE ROLE_RSRC_MAPP ADD (
     BLC_ID NUMBER -- Admin사업자ID 
);

-- 이벤트 테이블 컬럼 추가
ALTER TABLE EVENT_MGMT ADD (
    BLC_ID NUMBER -- 사업자 ID
);

-- 문서 다운로드 요청 테이블 컬럼 추가
ALTER TABLE DOC_DL_REQ ADD (
    BLC_ID NUMBER -- 사업자 ID
);

-- 20210219
-- 오비즈용 발송을 위한 컬럼을 추가한다.
ALTER TABLE SURVEY ADD (
    SURVEY_AGRE_IMG_FILE_ID VARCHAR2(50),       -- FILE ID
    SURVEY_AGRE_IMG_FILE_ID_EXPIRY_DATE DATE    -- FILE ID Expiry date
);


-- # DML
1. 오비즈사업 관련 데이터를 입력하기 전에 아래와 같은 설정이 우선되어야 한다.

-- ## BLC 테이블 입력
-- 1. 비즈챗 사업 => BLC_ID : 1
-- 주의사항: 반드시 'BLC_'로 시작하는 문구로 한다. 로직/쿼리와 연관된다.
insert into blc (
    blc_id, blc_cd, blc_nm, crt_dttm, crt_user_id, crt_prgm_id, upd_dttm, upd_user_id, upd_prgm_id, blc_disp_nm
) values (1,'BLC_BIZCHAT','비즈챗(BIZCHAT)',SYSDATE,'INIT','INIT',SYSDATE,'INIT','INIT','비즈챗');
-- 2. 오비즈 사업 => BLC_ID : 10
insert into blc (
    blc_id, blc_cd, blc_nm, crt_dttm, crt_user_id, crt_prgm_id, upd_dttm, upd_user_id, upd_prgm_id, blc_disp_nm
) values (10,'BLC_OBIZ','오비즈(OBIZ)',SYSDATE,'INIT','INIT',SYSDATE,'INIT','INIT','오비즈');

-- ## RLC 테이블
-- 1. 기존 비즈챗 blcid로 전부 세팅한다.
update rlc set blc_id = 1;

-- ## ADMIN 테이블
-- 1. 기존 비즈챗 blcid로 전부 설정
update admin set blc_id = 1;

-- ## CUSTOM 테이블
-- 1. 기존 비즈챗 blcid로 전부 설정
update custom set blc_id = 1;

-- ## SEP_CUSTOM 테이블
-- 1. 기존 비즈챗 blcid로 전부 설정
update sep_custom set blc_id = 1;

-- ## NOTI 테이블
-- 1. 기존 비즈챗 blcid로 전부 설정
update noti set blc_id = 1;

-- ## FAQ 테이블
-- 1. 기존 비즈챗 blcid로 전부 설정
update faq set blc_id = 1;

-- ## QNA 테이블
-- 1. 기존 비즈챗 blcid로 전부 설정
update qna set blc_id = 1;

-- ## COM_CD 테이블
-- 1. 공통 코드에서 코드 종류 'RLC_TP_CD' 인것만 세팅
update com_cd set blc_id = 1 where cd_grp_id = 'RLC_TP_CD'
-- 2. 오비즈 중계사도 입력을 하도록 한다. (주의: blc_id 충돌이 안나야 한다.)

-- ## EVENT_MGMT 테이블
-- 1. 공통 코드에서 코드 종류 'RLC_TP_CD' 인것만 세팅
update EVENT_MGMT set blc_id = 1;

-- ## EVENT_MGMT 테이블
-- 1. 공통 코드에서 코드 종류 'RLC_TP_CD' 인것만 세팅
update DOC_DL_REQ set blc_id = 1;

-- ## ROLE 테이블 (오비즈용 롤 생성)
-- ### OBIZ WEB ROLE
insert into role (role_id, role_tp_cd, prt_ord, role_nm, role_descr, use_yn, crt_dttm, crt_user_id, crt_prgm_id, upd_dttm, upd_user_id, upd_prgm_id, domain_tp_cd)
select 200, 'CUAD_OBIZ', prt_ord, '오비즈고객사 관리자', '오비즈고객사 관리자', use_yn, SYSDATE, crt_user_id, crt_prgm_id, SYSDATE, upd_user_id, upd_prgm_id, domain_tp_cd from role where role_id = 101;

insert into role (role_id, role_tp_cd, prt_ord, role_nm, role_descr, use_yn, crt_dttm, crt_user_id, crt_prgm_id, upd_dttm, upd_user_id, upd_prgm_id, domain_tp_cd)
select 202, 'CANONY_OBIZ', prt_ord, '오비즈Customer Anonymous', '오비즈Customer Anonymous', use_yn, SYSDATE, crt_user_id, crt_prgm_id, SYSDATE, upd_user_id, upd_prgm_id, domain_tp_cd from role where role_id = 102;

insert into role (role_id, role_tp_cd, prt_ord, role_nm, role_descr, use_yn, crt_dttm, crt_user_id, crt_prgm_id, upd_dttm, upd_user_id, upd_prgm_id, domain_tp_cd)
select 204, 'CUOP_OBIZ', prt_ord, '오비즈 리포트', '고객사 리포트', use_yn, SYSDATE, crt_user_id, crt_prgm_id, SYSDATE, upd_user_id, upd_prgm_id, domain_tp_cd from role where role_id = 104;

insert into role (role_id, role_tp_cd, prt_ord, role_nm, role_descr, use_yn, crt_dttm, crt_user_id, crt_prgm_id, upd_dttm, upd_user_id, upd_prgm_id, domain_tp_cd)
select 205, 'CUOP_OBIZ', prt_ord, '오비즈 다운로드', '고객사 자료실', use_yn, SYSDATE, crt_user_id, crt_prgm_id, SYSDATE, upd_user_id, upd_prgm_id, domain_tp_cd from role where role_id = 105;

insert into role (role_id, role_tp_cd, prt_ord, role_nm, role_descr, use_yn, crt_dttm, crt_user_id, crt_prgm_id, upd_dttm, upd_user_id, upd_prgm_id, domain_tp_cd)
select 206, 'CUOP_OBIZ', prt_ord, '오비즈 서버정보관리', '고객사 서버정보관리', use_yn, SYSDATE, crt_user_id, crt_prgm_id, SYSDATE, upd_user_id, upd_prgm_id, domain_tp_cd from role where role_id = 106;

insert into role (role_id, role_tp_cd, prt_ord, role_nm, role_descr, use_yn, crt_dttm, crt_user_id, crt_prgm_id, upd_dttm, upd_user_id, upd_prgm_id, domain_tp_cd)
select 209, 'CUOP_OBIZ', prt_ord, '서비스관리(설문조사)', '고객사 설문오비즈 관리', use_yn, SYSDATE, crt_user_id, crt_prgm_id, SYSDATE, upd_user_id, upd_prgm_id, domain_tp_cd from role where role_id = 109;

-- ### OBIZ ADMIN ROLE
insert into role (role_id, role_tp_cd, prt_ord, role_nm, role_descr, use_yn, crt_dttm, crt_user_id, crt_prgm_id, upd_dttm, upd_user_id, upd_prgm_id, domain_tp_cd)
select 251, 'SUA_OBIZ', prt_ord, '오비즈 Super Admin', '오비즈 Super Admin', use_yn, SYSDATE, crt_user_id, crt_prgm_id, SYSDATE, upd_user_id, upd_prgm_id, domain_tp_cd from role where role_id = 51;

insert into role (role_id, role_tp_cd, prt_ord, role_nm, role_descr, use_yn, crt_dttm, crt_user_id, crt_prgm_id, upd_dttm, upd_user_id, upd_prgm_id, domain_tp_cd)
select 252, 'ADM_OBIZ', prt_ord, '오비즈 사업자 Admin', '오비즈 Admin 시스템 관리자 계정 생성 제외한 모든 권한', use_yn, SYSDATE, crt_user_id, crt_prgm_id, SYSDATE, upd_user_id, upd_prgm_id, domain_tp_cd from role where role_id = 52;

insert into role (role_id, role_tp_cd, prt_ord, role_nm, role_descr, use_yn, crt_dttm, crt_user_id, crt_prgm_id, upd_dttm, upd_user_id, upd_prgm_id, domain_tp_cd)
select 260, 'RLC_OBIZ', prt_ord, '오비즈 중계사 Admin', '오비즈 중계사 Admin', use_yn, SYSDATE, crt_user_id, crt_prgm_id, SYSDATE, upd_user_id, upd_prgm_id, domain_tp_cd from role where role_id = 60;

insert into role (role_id, role_tp_cd, prt_ord, role_nm, role_descr, use_yn, crt_dttm, crt_user_id, crt_prgm_id, upd_dttm, upd_user_id, upd_prgm_id, domain_tp_cd)
select 270, 'DLC_OBIZ', prt_ord, '오비즈 딜러사 Admin', '오비즈 딜러사 Admin', use_yn, SYSDATE, crt_user_id, crt_prgm_id, SYSDATE, upd_user_id, upd_prgm_id, domain_tp_cd from role where role_id = 70;

insert into role (role_id, role_tp_cd, prt_ord, role_nm, role_descr, use_yn, crt_dttm, crt_user_id, crt_prgm_id, upd_dttm, upd_user_id, upd_prgm_id, domain_tp_cd)
select 254, 'OPR_OBIZ', prt_ord, '오비즈 Operator', '오비즈 Admin 시스템 메시지 관련 조회 권한', use_yn, SYSDATE, crt_user_id, crt_prgm_id, SYSDATE, upd_user_id, upd_prgm_id, domain_tp_cd from role where role_id = 54;

insert into role (role_id, role_tp_cd, prt_ord, role_nm, role_descr, use_yn, crt_dttm, crt_user_id, crt_prgm_id, upd_dttm, upd_user_id, upd_prgm_id, domain_tp_cd)
select 255, 'DEV_OBIZ', prt_ord, '오비즈 Developer', '오비즈 Admin 시스템 개발자 권한', use_yn, SYSDATE, crt_user_id, crt_prgm_id, SYSDATE, upd_user_id, upd_prgm_id, domain_tp_cd from role where role_id = 55;

-- ## RSRC 테이블 (오비즈용 리소스 생성)
-- ### 오비즈 WEB 리소스
INSERT INTO RSRC (RSRC_ID, UP_RSRC_ID, RSRC_NM, RSRC_DESCR, RSRC_URL, RSRC_TP_CD, DOMAIN_TP_CD, PRT_ORD, PRT_LVL, USE_YN, PRGM_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID) VALUES(2649, 501, '마케팅오비즈', '상품소개 > 설문비즈챗', '/main#bizChatGuideSv', 'M', 'CUSTOMER',4,2,'Y', NULL,SYSDATE, 'INIT', 'INIT', SYSDATE, 'INIT', 'INIT');
INSERT INTO RSRC (RSRC_ID, UP_RSRC_ID, RSRC_NM, RSRC_DESCR, RSRC_URL, RSRC_TP_CD, DOMAIN_TP_CD, PRT_ORD, PRT_LVL, USE_YN, PRGM_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID) VALUES(2651, 502, '마케팅오비즈', '리포트 > 설문비즈챗', '/statistics/main/sv', 'M', 'CUSTOMER',4,2,'Y', NULL,SYSDATE, 'INIT', 'INIT', SYSDATE, 'INIT', 'INIT');
INSERT INTO RSRC (RSRC_ID, UP_RSRC_ID, RSRC_NM, RSRC_DESCR, RSRC_URL, RSRC_TP_CD, DOMAIN_TP_CD, PRT_ORD, PRT_LVL, USE_YN, PRGM_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID) VALUES(2652, 2651, '설문통계(상세 리포트)', '리포트 > 설문비즈챗 > 설문통계(상세 리포트)', '/statistics/detail/report/sv', 'P', 'CUSTOMER',1,3,'Y', NULL,SYSDATE, 'INIT', 'INIT', SYSDATE, 'INIT', 'INIT');
INSERT INTO RSRC (RSRC_ID, UP_RSRC_ID, RSRC_NM, RSRC_DESCR, RSRC_URL, RSRC_TP_CD, DOMAIN_TP_CD, PRT_ORD, PRT_LVL, USE_YN, PRGM_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID) VALUES(2653, 2651, '설문통계(상세 리포트) 엑셀 다운로드', '리포트 > 설문비즈챗 > 설문통계(상세 리포트) > 엑셀 다운로드', '/statistics/detail/excel/sv', 'F', 'CUSTOMER',2,3,'Y', NULL,SYSDATE, 'INIT', 'INIT', SYSDATE, 'INIT', 'INIT');
INSERT INTO RSRC (RSRC_ID, UP_RSRC_ID, RSRC_NM, RSRC_DESCR, RSRC_URL, RSRC_TP_CD, DOMAIN_TP_CD, PRT_ORD, PRT_LVL, USE_YN, PRGM_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID) VALUES(2654, 2651, '설문통계(설문 이력 조회)', '리포트 > 설문비즈챗 > 설문통계(설문 이력 조회)', '/statistics/detail/hist/sv', 'P', 'CUSTOMER',3,3,'Y', NULL,SYSDATE, 'INIT', 'INIT', SYSDATE, 'INIT', 'INIT');
INSERT INTO RSRC (RSRC_ID, UP_RSRC_ID, RSRC_NM, RSRC_DESCR, RSRC_URL, RSRC_TP_CD, DOMAIN_TP_CD, PRT_ORD, PRT_LVL, USE_YN, PRGM_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID) VALUES(2655, 2651, '설문통계(설문 이력 조회) 엑셀 다운로드', '리포트 > 설문비즈챗 > 설문통계(설문 이력 조회) > 엑셀 다운로드', '/statistics/detail/hist/excel/sv', 'F', 'CUSTOMER',4,3,'Y', NULL,SYSDATE, 'INIT', 'INIT', SYSDATE, 'INIT', 'INIT');
INSERT INTO RSRC (RSRC_ID, UP_RSRC_ID, RSRC_NM, RSRC_DESCR, RSRC_URL, RSRC_TP_CD, DOMAIN_TP_CD, PRT_ORD, PRT_LVL, USE_YN, PRGM_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID) VALUES(2658, 2651, '발신문자 실패 내역 통계', '리포트 > 설문비즈챗 > 실패 내역 통계', '/statistics/fail/sv/mt', 'P', 'CUSTOMER',7,3,'Y', NULL,SYSDATE, 'INIT', 'INIT', SYSDATE, 'INIT', 'INIT');
INSERT INTO RSRC (RSRC_ID, UP_RSRC_ID, RSRC_NM, RSRC_DESCR, RSRC_URL, RSRC_TP_CD, DOMAIN_TP_CD, PRT_ORD, PRT_LVL, USE_YN, PRGM_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID) VALUES(2659, 2651, '수신문자 실패 내역 통계', '리포트 > 설문비즈챗 > 실패 내역 통계', '/statistics/fail/sv/mo', 'P', 'CUSTOMER',8,3,'Y', NULL,SYSDATE, 'INIT', 'INIT', SYSDATE, 'INIT', 'INIT');
INSERT INTO RSRC (RSRC_ID, UP_RSRC_ID, RSRC_NM, RSRC_DESCR, RSRC_URL, RSRC_TP_CD, DOMAIN_TP_CD, PRT_ORD, PRT_LVL, USE_YN, PRGM_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID) VALUES(2660, 2651, '실패 내역 엑셀다운로드', '리포트 > 설문비즈챗 > 실패 내역 엑셀다운로드', '/statistics/fail/excel/sv/mt', 'F', 'CUSTOMER',9,3,'Y', NULL,SYSDATE, 'INIT', 'INIT', SYSDATE, 'INIT', 'INIT');
INSERT INTO RSRC (RSRC_ID, UP_RSRC_ID, RSRC_NM, RSRC_DESCR, RSRC_URL, RSRC_TP_CD, DOMAIN_TP_CD, PRT_ORD, PRT_LVL, USE_YN, PRGM_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID) VALUES(2661, 2651, '실패 내역 엑셀다운로드', '리포트 > 설문비즈챗 > 실패 내역 엑셀다운로드', '/statistics/fail/excel/sv/mo', 'F', 'CUSTOMER',10,3,'Y', NULL,SYSDATE, 'INIT', 'INIT', SYSDATE, 'INIT', 'INIT');
INSERT INTO RSRC (RSRC_ID, UP_RSRC_ID, RSRC_NM, RSRC_DESCR, RSRC_URL, RSRC_TP_CD, DOMAIN_TP_CD, PRT_ORD, PRT_LVL, USE_YN, PRGM_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID) VALUES(2662, 2651, '설문 리스트 불러오기', '리포트 > 설문비즈챗 > 설문리스트 불러오기', '/statistics/sv/survey/list', 'F', 'CUSTOMER',5,3,'Y', NULL,SYSDATE, 'INIT', 'INIT', SYSDATE, 'INIT', 'INIT');
INSERT INTO RSRC (RSRC_ID, UP_RSRC_ID, RSRC_NM, RSRC_DESCR, RSRC_URL, RSRC_TP_CD, DOMAIN_TP_CD, PRT_ORD, PRT_LVL, USE_YN, PRGM_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID) VALUES(2591, 506, '발신번호 관리', '마이페이지 > 발신번호 관리', '/myPage/callerIdManage', 'M', 'CUSTOMER',4,2,'Y', NULL,SYSDATE, 'INIT', 'INIT', SYSDATE, 'INIT', 'INIT');
INSERT INTO RSRC (RSRC_ID, UP_RSRC_ID, RSRC_NM, RSRC_DESCR, RSRC_URL, RSRC_TP_CD, DOMAIN_TP_CD, PRT_ORD, PRT_LVL, USE_YN, PRGM_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID) VALUES(2593, 2591, '발신번호 저장', '마이페이지 > 발신번호 관리 > 발신번호 저장', '/myPage/saveSpcNum', 'F', 'CUSTOMER',1,3,'Y', NULL,SYSDATE, 'INIT', 'INIT', SYSDATE, 'INIT', 'INIT');
INSERT INTO RSRC (RSRC_ID, UP_RSRC_ID, RSRC_NM, RSRC_DESCR, RSRC_URL, RSRC_TP_CD, DOMAIN_TP_CD, PRT_ORD, PRT_LVL, USE_YN, PRGM_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID) VALUES(2594, 2591, '발신번호 체크', '마이페이지 > 발신번호 관리 > 발신번호 체크', '/myPage/checkSpcNum', 'F', 'CUSTOMER',2,3,'Y', NULL,SYSDATE, 'INIT', 'INIT', SYSDATE, 'INIT', 'INIT');
INSERT INTO RSRC (RSRC_ID, UP_RSRC_ID, RSRC_NM, RSRC_DESCR, RSRC_URL, RSRC_TP_CD, DOMAIN_TP_CD, PRT_ORD, PRT_LVL, USE_YN, PRGM_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID) VALUES(2524, 506, '나의 1:1 문의', '마이페이지 > 나의 1:1 문의', '/myPage/qnaList', 'M', 'CUSTOMER',5,2,'Y', NULL,SYSDATE, 'INIT', 'INIT', SYSDATE, 'INIT', 'INIT');
INSERT INTO RSRC (RSRC_ID, UP_RSRC_ID, RSRC_NM, RSRC_DESCR, RSRC_URL, RSRC_TP_CD, DOMAIN_TP_CD, PRT_ORD, PRT_LVL, USE_YN, PRGM_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID) VALUES(2619, NULL, '서비스 관리', '서비스 관리', '/project/projectManage', 'M', 'CUSTOMER',3,1,'Y', NULL,SYSDATE, 'INIT', 'INIT', SYSDATE, 'INIT', 'INIT');
INSERT INTO RSRC (RSRC_ID, UP_RSRC_ID, RSRC_NM, RSRC_DESCR, RSRC_URL, RSRC_TP_CD, DOMAIN_TP_CD, PRT_ORD, PRT_LVL, USE_YN, PRGM_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID) VALUES(2634, 2619, '설문조사', '서비스 관리 > 설문조사', '/project/projectManage', 'M', 'CUSTOMER',3,2,'Y', NULL,SYSDATE, 'INIT', 'INIT', SYSDATE, 'INIT', 'INIT');
INSERT INTO RSRC (RSRC_ID, UP_RSRC_ID, RSRC_NM, RSRC_DESCR, RSRC_URL, RSRC_TP_CD, DOMAIN_TP_CD, PRT_ORD, PRT_LVL, USE_YN, PRGM_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID) VALUES(2635, 2634, '설문 관리', '서비스 관리 > 설문조사 > 설문 관리', '/survey/list', 'P', 'CUSTOMER',3,3,'Y', NULL,SYSDATE, 'INIT', 'INIT', SYSDATE, 'INIT', 'INIT');
INSERT INTO RSRC (RSRC_ID, UP_RSRC_ID, RSRC_NM, RSRC_DESCR, RSRC_URL, RSRC_TP_CD, DOMAIN_TP_CD, PRT_ORD, PRT_LVL, USE_YN, PRGM_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID) VALUES(2636, 2634, '설문 제작', '서비스 관리 > 설문조사 > 설문 제작', '/survey/registSurvey', 'P', 'CUSTOMER',2,3,'Y', NULL,SYSDATE, 'INIT', 'INIT', SYSDATE, 'INIT', 'INIT');
INSERT INTO RSRC (RSRC_ID, UP_RSRC_ID, RSRC_NM, RSRC_DESCR, RSRC_URL, RSRC_TP_CD, DOMAIN_TP_CD, PRT_ORD, PRT_LVL, USE_YN, PRGM_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID) VALUES(2637, 2636, '설문 저장', '서비스 관리 > 설문조사 > 설문 제작 > 설문 저장', '/survey/saveSurvey', 'F', 'CUSTOMER',2,4,'Y', NULL,SYSDATE, 'INIT', 'INIT', SYSDATE, 'INIT', 'INIT');
INSERT INTO RSRC (RSRC_ID, UP_RSRC_ID, RSRC_NM, RSRC_DESCR, RSRC_URL, RSRC_TP_CD, DOMAIN_TP_CD, PRT_ORD, PRT_LVL, USE_YN, PRGM_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID) VALUES(2638, 2635, '설문 상세 정보', '서비스 관리 > 설문조사 > 설문 관리 > 설문 상세정보', '/survey/detail', 'P', 'CUSTOMER',1,4,'Y', NULL,SYSDATE, 'INIT', 'INIT', SYSDATE, 'INIT', 'INIT');
INSERT INTO RSRC (RSRC_ID, UP_RSRC_ID, RSRC_NM, RSRC_DESCR, RSRC_URL, RSRC_TP_CD, DOMAIN_TP_CD, PRT_ORD, PRT_LVL, USE_YN, PRGM_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID) VALUES(2639, 2635, '설문 상세 정보 가져오기', '서비스 관리 > 설문조사 > 설문 관리 > 설문 상세정보', '/survey/detailinfo', 'F', 'CUSTOMER',2,4,'Y', NULL,SYSDATE, 'INIT', 'INIT', SYSDATE, 'INIT', 'INIT');
INSERT INTO RSRC (RSRC_ID, UP_RSRC_ID, RSRC_NM, RSRC_DESCR, RSRC_URL, RSRC_TP_CD, DOMAIN_TP_CD, PRT_ORD, PRT_LVL, USE_YN, PRGM_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID) VALUES(2640, 2635, '설문 이미지 불러오기', '서비스 관리 > 설문조사 > 설문 관리 > 설문 상세정보', '/survey/imgLoad', 'F', 'CUSTOMER',3,4,'Y', NULL,SYSDATE, 'INIT', 'INIT', SYSDATE, 'INIT', 'INIT');
INSERT INTO RSRC (RSRC_ID, UP_RSRC_ID, RSRC_NM, RSRC_DESCR, RSRC_URL, RSRC_TP_CD, DOMAIN_TP_CD, PRT_ORD, PRT_LVL, USE_YN, PRGM_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID) VALUES(2642, 2636, '임시저장함', '서비스 관리 > 설문조사 > 설문 제작 > 임시저장함', '/survey/tempSurveyListPupUp', 'P', 'CUSTOMER',1,4,'Y', NULL,SYSDATE, 'INIT', 'INIT', SYSDATE, 'INIT', 'INIT');
INSERT INTO RSRC (RSRC_ID, UP_RSRC_ID, RSRC_NM, RSRC_DESCR, RSRC_URL, RSRC_TP_CD, DOMAIN_TP_CD, PRT_ORD, PRT_LVL, USE_YN, PRGM_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID) VALUES(2643, 2636, '설문 임시저장', '서비스 관리 > 설문조사 > 설문 제작 > 설문 임시저장', '/survey/tempSaveSurvey', 'F', 'CUSTOMER',3,4,'Y', NULL,SYSDATE, 'INIT', 'INIT', SYSDATE, 'INIT', 'INIT');
INSERT INTO RSRC (RSRC_ID, UP_RSRC_ID, RSRC_NM, RSRC_DESCR, RSRC_URL, RSRC_TP_CD, DOMAIN_TP_CD, PRT_ORD, PRT_LVL, USE_YN, PRGM_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID) VALUES(2644, 2636, '설문 삭제', '서비스 관리 > 설문조사 > 설문 제작 > 설문 임시저장함 > 설문 삭제', '/survey/tempSurvey', 'F', 'CUSTOMER',4,5,'Y', NULL,SYSDATE, 'INIT', 'INIT', SYSDATE, 'INIT', 'INIT');
INSERT INTO RSRC (RSRC_ID, UP_RSRC_ID, RSRC_NM, RSRC_DESCR, RSRC_URL, RSRC_TP_CD, DOMAIN_TP_CD, PRT_ORD, PRT_LVL, USE_YN, PRGM_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID) VALUES(2645, 2636, '템플릿 다운로드', '서비스 관리 > 설문조사 > 설문 제작 > 템플릿 다운로드', '/survey/templateDownload', 'F', 'CUSTOMER',5,4,'Y', NULL,SYSDATE, 'INIT', 'INIT', SYSDATE, 'INIT', 'INIT');
INSERT INTO RSRC (RSRC_ID, UP_RSRC_ID, RSRC_NM, RSRC_DESCR, RSRC_URL, RSRC_TP_CD, DOMAIN_TP_CD, PRT_ORD, PRT_LVL, USE_YN, PRGM_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID) VALUES(2646, 2635, '수신자 번호 엑셀 다운로드', '서비스 관리 > 설문조사 > 설문 관리 > 수신자 번호 엑셀 다운로드', '/survey/downloadRcverExcel', 'F', 'CUSTOMER',4,4,'Y', NULL,SYSDATE, 'INIT', 'INIT', SYSDATE, 'INIT', 'INIT');
INSERT INTO RSRC (RSRC_ID, UP_RSRC_ID, RSRC_NM, RSRC_DESCR, RSRC_URL, RSRC_TP_CD, DOMAIN_TP_CD, PRT_ORD, PRT_LVL, USE_YN, PRGM_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID) VALUES(2647, 2635, '설문 상태 변경', '서비스 관리 > 설문조사 > 설문 관리 > 설문 상태 변경', '/survey/updateState', 'F', 'CUSTOMER',4,4,'Y', NULL,SYSDATE, 'INIT', 'INIT', SYSDATE, 'INIT', 'INIT');
INSERT INTO RSRC (RSRC_ID, UP_RSRC_ID, RSRC_NM, RSRC_DESCR, RSRC_URL, RSRC_TP_CD, DOMAIN_TP_CD, PRT_ORD, PRT_LVL, USE_YN, PRGM_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID) VALUES(2648, 2635, '설문 엑셀 다운로드', '서비스 관리 > 설문조사 > 설문 관리 > 설문 엑셀 다운로드', '/survey/surveyDownload', 'F', 'CUSTOMER',5,4,'Y', NULL,SYSDATE, 'INIT', 'INIT', SYSDATE, 'INIT', 'INIT');
INSERT INTO RSRC (RSRC_ID, UP_RSRC_ID, RSRC_NM, RSRC_DESCR, RSRC_URL, RSRC_TP_CD, DOMAIN_TP_CD, PRT_ORD, PRT_LVL, USE_YN, PRGM_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID) VALUES(2650, 2635, '설문 결과 다운로드', '서비스 관리 > 설문조사 > 설문 관리 > 설문 결과 다운로드', '/survey/downloadResultExcel', 'F', 'CUSTOMER',5,4,'Y', NULL,SYSDATE, 'INIT', 'INIT', SYSDATE, 'INIT', 'INIT');
INSERT INTO RSRC (RSRC_ID, UP_RSRC_ID, RSRC_NM, RSRC_DESCR, RSRC_URL, RSRC_TP_CD, DOMAIN_TP_CD, PRT_ORD, PRT_LVL, USE_YN, PRGM_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID) VALUES(2663, 2636, '설문 특번 기간 불러오기', '서비스 관리 > 설문조사 > 설문 제작 > 설문 특번 기간 불러오기', '/survey/spcnum/list', 'F', 'CUSTOMER',6,4,'Y', NULL,SYSDATE, 'INIT', 'INIT', SYSDATE, 'INIT', 'INIT');
INSERT INTO RSRC (RSRC_ID, UP_RSRC_ID, RSRC_NM, RSRC_DESCR, RSRC_URL, RSRC_TP_CD, DOMAIN_TP_CD, PRT_ORD, PRT_LVL, USE_YN, PRGM_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID) VALUES(2665, 2636, '엑셀 업로드 벨리데이션 체크', '서비스 관리 > 설문조사 > 설문 제작 > 엑셀 업로드 벨리데이션 체크', '/survey/excel/validation', 'F', 'CUSTOMER',7,4,'Y', NULL,SYSDATE, 'INIT', 'INIT', SYSDATE, 'INIT', 'INIT');


-- ## ROLE_RSRC_MAPP 테이블 (오비즈용 맵핑 생성)
-- ### 오비즈 WEB 리포트 권한
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 500, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 501, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 502, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 504, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 505, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 506, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 516, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 517, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 518, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 519, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 521, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 555, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 556, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 557, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 558, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 559, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 560, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 561, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 564, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 565, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 576, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 577, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 578, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 579, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 580, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 581, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 582, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 583, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 584, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 607, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 608, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 609, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 633, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 665, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 666, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 2014, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 2015, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 2016, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 2017, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 2103, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 2104, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 2107, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 2108, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 2122, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 2123, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 2524, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 2649, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 2651, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 2654, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 2655, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(204, 2662, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);

-- ### 오비즈 WEB 다운로드 권한
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(205, 500, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(205, 501, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(205, 504, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(205, 505, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(205, 506, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(205, 516, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(205, 517, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(205, 518, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(205, 519, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(205, 520, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(205, 521, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(205, 555, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(205, 556, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(205, 557, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(205, 558, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(205, 559, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(205, 560, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(205, 561, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(205, 562, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(205, 563, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(205, 564, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(205, 565, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(205, 576, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(205, 577, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(205, 578, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(205, 579, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(205, 580, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(205, 581, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(205, 582, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(205, 583, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(205, 584, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(205, 607, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(205, 608, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(205, 609, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(205, 633, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(205, 1001, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(205, 2649, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(205, 2524, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);


-- ### 오비즈 WEB 서버정보관리 권한
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(206, 500, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(206, 501, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(206, 504, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(206, 505, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(206, 506, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(206, 516, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(206, 517, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(206, 518, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(206, 519, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(206, 521, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(206, 523, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(206, 555, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(206, 556, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(206, 557, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(206, 558, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(206, 559, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(206, 560, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(206, 561, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(206, 564, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(206, 565, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(206, 566, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(206, 567, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(206, 568, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(206, 569, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(206, 576, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(206, 577, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(206, 578, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(206, 579, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(206, 580, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(206, 581, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(206, 582, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(206, 583, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(206, 584, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(206, 607, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(206, 608, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(206, 609, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(206, 633, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(206, 2524, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(206, 1004, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(206, 2649, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);


-- ### 오비즈 WEB 서비스관리 권한
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 500, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 501, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 504, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 505, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 506, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 516, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 517, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 518, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 519, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 521, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 555, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 556, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 557, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 558, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 559, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 560, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 561, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 564, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 565, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 576, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 577, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 578, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 579, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 580, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 581, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 582, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 583, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 584, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 607, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 608, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 609, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 633, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 2003, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 2004, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 2005, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 2006, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 2007, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 2008, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 2009, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 2101, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 2102, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 2105, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 2106, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 2112, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 2113, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 2114, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 2118, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 2119, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 2121, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 2124, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 2125, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 2126, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 2128, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 2129, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 2524, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 2619, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 2634, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 2635, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 2636, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 2637, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 2638, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 2639, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 2640, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 2642, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 2643, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 2644, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 2645, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 2646, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 2647, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 2648, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 2650, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 2663, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 2665, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
INSERT INTO ROLE_RSRC_MAPP (ROLE_ID, RSRC_ID, CRT_DTTM, CRT_USER_ID, CRT_PRGM_ID, UPD_DTTM, UPD_USER_ID, UPD_PRGM_ID, BLC_ID) VALUES(209, 2649, SYSDATE, 'init', 'init', SYSDATE, 'init', 'init', 10);
